name: Build page

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Install deps
        run: npm i --legacy-peer-deps

      - name: Install typescript
        run: npm install -g typescript

      - name: Download images
        run: cd src/ && tsc build.ts && node build.js && cd ../

      - name: Clean js files
        run: rm src/build.js src/api/album.js src/data/albums.js

      - name: Build
        run: npm run build

      - name: Copy images
        run: cp src/assets/* dist/assets

      - name: Deploy
        uses: crazy-max/ghaction-github-pages@v4
        with:
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
